[package]
name = "fragmentable"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize", "debug"] }
bincode = { version = "2.0.0-rc", features = ["serde"] }
